spring:
  application:
    name: shortlink
  datasource:
    url: jdbc:postgresql://localhost:5432/shortenerdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  redis:
    host: redis
    port: 6379
  jpa:
    hibernate:
      ddl-auto: none    # use schema.sql or Flyway for schema creation
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always      # ensures schema.sql runs at startup
